nomlab/swimmy

.gitignore
FBot.rb
Gemfile
Gemfile.lock
SlackBot.rb
Swimmy.rb
config.ru
settings.yml.sample
test/post_test.rb
test/test.json

swimmy に，藤原が研修課題で作成した SlackBot の機能を追加した．
追加した機能は，移動手段と出発地点と到着地点から経路に関する情報を教えてくれる機能である．

Add FBot to swimmy

---

SYBot.rb
Swimmy.rb

swimmyに，吉田が研修課題で作成したSlackBotの機能を追加した．
追加した機能は以下のとおりである．
1. GitHubのnomrab/nompediaのIssues一覧を取得する機能
2. GitHubのnomrab/nompediaのIssuesに新たにissueを作成する機能

Add SYBot to swimmy

---

Swimmy.rb
TakaBot.rb
settings.yml.sample

swimmyに，高橋が研修課題で作成したSlackBotの機能を追加した．
追加した機能は，入力された飲食店の詳細情報を表示する機能である．

Add TakaBot to swimmy

---

test/test.json

test/test.json の1行目を
{"user_name": "user_name", "text": "@Swimmy test_message\n"}
に修正しました．

Modify text in test/test.json

---

SYBot.rb
Swimmy.rb
settings.yml.sample

以下の点を変更しました．
1.Swimmy.rbにおいて，SwimmyがSYBotをincludeするように修正
2.settings.yml.sampleにUSERNAMEとPASSWORDを追加
3.SYBot.rbにおいて，GITHUB_APIを初期化

Add USERNAME and PASSWORD templates

---

SYBot.rb
SlackBot.rb
settings.yml.sample
test/test1.json

SYBot.rb内のSYBotモジュールで使用する以下の変数について，その値をHerokuの環境変数から読み込めるように修正しました．
1.@git_username
2.@git_password

Add reading environment variable to SlackBot.rb

---

SlackBot.rb
TakaBot.rb
settings.yml.sample

以下の2つを行った．
- ```SlackBot.rb``` に Heroku 用の環境変数を読み込むための機能を追加し，インスタンス変数を作成した．
- 上記で作成したインスタンス変数を ```TakaBot.rb``` で使用するように変更した．

Add an environment variable to SlackBot.rb

---

Gemfile
Gemfile.lock

#15 に対してのPRである．
Gemfile に記述されている sinatra のバージョンを2.0.1から2.0.2に変更した．
これにより，Gemfile.lock に記述されている Gem のバージョンが変更された．

Update sinatra version 2.0.1 to 2.0.2

---

Gemfile.lock
SYBot.rb

get issue を使用した際，issueのタイトルだけでなく，issueのページへのリンクも送信するようにSYBotを修正しました．

Modify SYBot to output link to each issue

---

SYBot.rb

Fix a bug in SYbot

---

FBot.rb
Swimmy.rb

#18 に対するPRである．
「発言を処理し，処理結果を swimmy が発言し，その内容から再度 swimmy が処理をし発言する．」を繰り返し無限ループするバグを修正した．
加えて，FBot.rb に swimmy と同様の修正をした．

Fix infinite loop bug

---

lib/swimmy/command.rb
lib/swimmy/command/qiita_trend.rb

平日の12時に Qiita からいいねの数が100以上の記事を3件取ってきて，Slack に投稿する機能を追加した．
以下に投稿の例を示す．
```
本日のおすすめ記事です!
https://qiita.com/ampersand/items/7180f657b3d0a0c05734
いいね数 516
https://qiita.com/fujit33/items/dbfbd7a2aa3858067b6c
いいね数 721
https://qiita.com/_somary/items/ac55db148b72726d0753
いいね数 307
```

Add qiita_trend.rb

---

README.md
systemd_conf/swimmy.service
systemd_conf/swimmy_env

#39 #40 へのPR
以下の2点を行なった．
+ systemdでswimmyを動かすための設定に必要なファイルをリポジトリに保存 (eb3992f)
+ README.mdにsystemdでswimmyを動かすための設定を記述(b3ba9cb)
+ `systemd_conf`ディレクトリを作成し，以下の2つのファイルを配置
+ `swimmy.service`
systemdでの動作設定を記述するためのファイル
+ `swimmy_env`
systemdでの動作に必要な環境変数を記述するためのファイル
+ Settingsにsystemdでswimmyを動作させるために必要な設定を記述
+ Runにsystemdでswimmyを起動させる方法と停止させる方法を記述

Add systemd setting files

---

lib/swimmy/command/lottery.rb
lib/swimmy/command/nomnichi.rb
lib/swimmy/resource.rb
lib/swimmy/resource/member.rb

sheetq で使用する member resource を `Swimmy::Resource::Member` に移した．

Move member resource from sheetq

---

README.md
systemd_conf/user/swimmy.service

#40 の追加PR
+ 非 root ユーザで systemd を使用する場合の設定ファイルの追加
+ 上記に伴うREADMEの追記

Add user mode systemd_conf

---

.github/workflows/swimmy.yml
.gitignore
Gemfile
Gemfile.lock
spec/swimmy_spec.rb

#46 へのPR
+ RSpec の追加
+ rspec を Gemfile へ追記
+ .gitignore へ rspec の ログファイルを追記
+ GitHub Actions の設定ファイルを追加

Add GitHub Actions conf

---

Gemfile.lock
lib/swimmy/command/attendance.rb
lib/swimmy/command/base.rb
lib/swimmy/resource.rb
lib/swimmy/resource/attendance.rb

Swimmy recognize hi/bye command

Add attendance logger

---

Gemfile
Gemfile.lock
lib/swimmy/app.rb

This is mitigation for https://github.com/slack-ruby/slack-ruby-bot/issues/236

Replace celluloid by async-websocket

---

lib/swimmy/command/weather_information.rb

Add weather_information

---

lib/swimmy/command/trivia.rb

Add trivia.rb

---

lib/swimmy/command/poll.rb

#57 に対するPRである．
+ pollコマンドのhelpがなかったため，helpを作成した．
+ helpの内容を以下に示す．
> poll - 集計を行います．
>
>poll title choice1,choice2,...
>titleは，集計題目です．choice1，choice2 は，選択肢です．選択肢が複数ある場合は，半角コンマで区切ってください．選択肢は最大9つまで入力できます．

Add poll command help

---

lib/swimmy/command/update.rb

#46 に関するPR
updateコマンドを追加した．
本コマンドは以下の動作を行う．
+ リモートリポジトリの変更をローカルブランチに取り込む．
+ gemをインストールする．

Add update command

---

lib/swimmy/command/search_conveni.rb

以下の点を修正したコンビニを検索するプログラムのPR
- 'GOOGLE_PLACES_API_KEY'を読み込むように修正
- 上記のAPI keyがない場合に，それを伝えるメッセージを表示するよう修正

Add search_conveni

---

Dockerfile
swimmy-docker.sh

swimmyをDockerを用いて起動できるようにDockerfileとswimmy-docker.shを追加した．
このPRは #68 に基づく．

add Dockerfile and swimmy-docker.sh

---

swimmy-docker.sh

#68 に対するPR
[第28回議事録](http://jay.swlab.cs.okayama-u.ac.jp/minutes/1034)と[第30回議事録](http://jay.swlab.cs.okayama-u.ac.jp/minutes/1057)に合わせ，swimmy-docker.shを修正した．

modified swimmy-docker.sh

---

lib/swimmy/command/say.rb

#74 に対するPR
指定した時間に指定した文字列を発言するコマンド

Add say command

---

lib/swimmy/command/memo.rb
lib/swimmy/resource.rb
lib/swimmy/resource/memo.rb

#75 に対するPR
Add memo command
メモを記録・表示する機能を実装した．
メモは，スプレッドシートに記録する．

Add memo command

---

lib/swimmy/command/today.rb

Fixed help message

---

lib/swimmy/command/update.rb

Modify update command

---

lib/swimmy/command/pokemon.rb
lib/swimmy/service.rb
lib/swimmy/service/pokemoninfo.rb

- ランダムでポケモンの情報を表示するpokemonコマンドの実装
- 乃村研B4向けの新人研修課題に取り組むため
- [新人研修課題](https://scrapbox.io/nompedia/swimmy_%E3%81%AE%E6%A9%9F%E8%83%BD%E8%BF%BD%E5%8A%A0)
/pokemon/と入力し，情報を表示する
- ランダムなポケモンの情報を取得する機能
- pokeapiというAPIを使用しましたhttps://pokeapi.co/
- ランダムな図鑑番号をrandメソッドで生成しています
- pokeapiが提供する複数のページから欲しい情報を集めています

add pokemon.rb & pokemoninfo.rb, modified service.rb

---

lib/swimmy/command/pokemon.rb
lib/swimmy/service/pokemoninfo.rb

- インデントのズレを修正した．
- オブジェクトを意識したコードに修正した．

Refactor pokemon command

---

lib/swimmy/command/lottery.rb

lottery コマンドで学年を指定できるように修正
* lottery.rb ファイルにスプレッドシートの学年の項目も読み取るように処理を追加
* 機能の変更に合わせて，help メッセージも変更

Allow lottery to take title as argument

---

lib/swimmy/command/stayave.rb

- stayaveコマンドの実装
lib/swimmy/command 以下に stayave.rb を追加した
- 平均出席時刻，平均帰宅時刻，平均滞在時間，データ数を表示する
- Slackのnomlabワークスペースで`swimmy stayave`を入力する
- Slackのnomlabワークスペースで`swimmy stayave <usr_name>`と入力する
- GoogleスプレッドシートAPIを使用している
- hi/byeコマンドで使用するGoogleスプレッドシートから出席時刻，帰宅時刻のデータを取得し，平均出席時刻，平均帰宅時刻，平均滞在時間を求める

Add stayave

---

lib/swimmy/command/w.rb

wコマンドの追加
lib/swimmy/command 以下に w.rb を追加した．
追加した後，関数名，一部機能を変更しました．
現在の在室者と退室者を表示する．
`swimmy w` と入力する．
Google Spread Sheet の API を使用している．

Add W command

---

lib/swimmy/command/photo_upload.rb

Fix syntax error

---

lib/swimmy/resource/member.rb

- スプレッドシートの colomn 追加に伴い，swimmy に追加したcolumn に対応する属性を持つように変更した．
lib/swimmy/resource/member.rbにbtnac属性を追加した

Add btmac attribute to Menber resource

---

lib/swimmy/command/nomnichi.rb

PR #116 と PR #117 の変更点を merge した．
- ノムニチの執筆候補を3人表示するように変更した．
- `list`オプションを追加した．
`swimmy nomnichi`: ノムニチ執筆候補を3人表示する．
`swimmy nomnichi list`: ノムニチ執筆候補全員を担当順に表示する．

Update nomnichi to show three candidates and add list option

---

lib/swimmy/command/photo_upload.rb

#112 の変更により，写真が投稿されたかに関わらずphoto-uploder が GoogleOAuth インスタンスを初期化するようになっていたため，写真が投稿された際のみインスタンスを作成するようにした．
写真をアップロードしていないにも関わらず，Google OAuth の警告が出る問題を解決するため．

Update photo-uploader not to initialize GoogleOAuth with each message

---

lib/swimmy/resource/schedule.rb

at コマンドによる自動実行時の「at コマンドによる実行です．」というメッセージを削除した．

Delete at command notification
