nomlab/swimmy

- FBot.rb
- SlackBot.rb
Heroku では API キーを環境変数で設定するため，環境変数を読み込めるように以下の点を編集しました．
+ SlackBot.rb に環境変数を読み込むための機能を追加し，インスタンス変数を作成
+ 上記で作成したインスタンス変数を FBot.rb で使用するように変更
> Add reading environment variable to SlackBot.rb

- SYBot.rb
- SlackBot.rb
- Swimmy.rb
- settings.yml.sample
get issue を使ったときの出力について，リンクをタイトル文字列に埋め込むよう修正しました．
(2018/6/13加筆)GitHubのwebhookを用いて，issueに関して以下のアクションが生じた場合に，slackへその旨を投稿する機能をSYBotに追加しました．
1.open
2.reopen
3.close
4.assign
5.unassign
6.edit
> Arrange output of SYBot

- .gitignore
- lib/swimmy/command/base.rb
- lib/swimmy/command/hide_defalts.rb
- lib/swimmy/command/issue_operation.rb
- lib/swimmy/command/rain_information.rb
- lib/swimmy/command/restaurant_information.rb
- lib/swimmy/command/route.rb
変更点は以下である．
- 各コマンドは SlackRubyBot::Command::Base を継承していた．これを，SlackRubyBot::Command::Base を継承する Base クラスを作成し，各コマンドは Base クラスを継承するように書き換えた．
- 各コマンドの public メソッドを，すべて private メソッドに変更した．
- .env ファイルを .gitignore に追加して，git の管理に含めないようにした．
> Add base class to inherit SlackRubyBot::Command::Base

- exe/google_photo_auth
- lib/swimmy/command.rb
- lib/swimmy/command/photo_upload.rb
+ Slack に投稿された画像（jpg または png）を Google フォトにアップロードする機能を追加した．
+ exe/google_photo_auth に OAuth 認証のためのスクリプトを作成した
現在，config/ ディレクトリ以下にクライアント ID 等が記述された joson ファイルが配置されていることを想定している．また，本 PR で追加した exe/google_photo_auth を実行すると access_token 等が記述された config/google-photo-token.json が作成される．
この token の配置場所については，他の認証を必要とする Bot と合わせて検討する必要がある．
1. Google Cloud Platform より認証情報をダウンロードする.
https://console.cloud.google.com/apis/credentials にアクセスし，「JSON をダウンロード」によりクライアント ID 等が記述された credentials.json をダウンロードできる．
2. credentials.json を config/ に配置
```
.
├── Gemfile
├── Gemfile.lock
├── LICENSE.txt
├── README.md
├── Rakefile
├── bin
│   ├── console
│   └── setup
├── config
│   ├── credentials.json
│   └── google-photo-token.json (次の手順３で生成される)
(以下略)
```
3. exe/google_photo_auth を実行
表示される URL にアクセスすると，Google …
> Google フォトに画像をアップロードする機能を追加した

- lib/swimmy/command.rb
- lib/swimmy/command/poll.rb
swimmy に投票機能を追加した．タイトルと選択肢を指定すると，slack のリアクションを用いた投票用メッセージが swimmy から送信される．
投票機能を利用するためには，以下に示す形式のメッセージを送信する．
`poll 投票の題目 選択肢1,選択肢2,...` 
例を以下に示す．
`poll 忘年会の出欠 参加,不参加`
適切なメッセージを送信したとき，swimmy から以下のようなメッセージが送信される．
投票したい番号に対応するリアクションをクリックすることで，投票でき，投票数がリアルタイムで更新される．
poll コマンドでは，リアクションをつける際，channel.history という API を利用している．
channel.history は，Bot 用の API トークンではなく，User 用の API トークンを用いる必要がある．
そこで，現在，poll コマンド内では，channel.history を用いるときに，一時的にトークンを切り替えている．
また，poll コマンドでは，各種 API トークンを記述する，`.env` というファイルに `SLACK_API_TOKEN_USER` というキーで User用の API トークンが記述されていることを想定している．
> Add poll command

- exe/swimmy
On catching some exceptions, swimmy main-loop creates a new bot instance.
In some cases, the old bot was still remained.
This patch makes swimmy kill the old bot surely before new ones are created.
> Remove old bot instances before restart

- .github/workflows/swimmy.yml
#46 に関するPR
GitHub Actionsのワークフローをトリガするイベントをpushからpull-requestに変更
> Change Actions trigger from push to pull-request

- exe/swimmy
- lib/swimmy/app.rb
- lib/swimmy/command/restart.rb
#45 と #56 に対するPRである．
swimmy の再起動をSlackからできるようにするための機能を追加した．
具体的には，以下を行なった．
+ `lib/swimmy/command` に`restart.rb`を作成し，Slackからrestartコマンドを実行すると再起動するようにした．
+ `lib/swimmy/app.rb` にswimmyを起動する際のオプションを追加し，swimmy起動時に，指定したメッセージがSlackに投稿されるようにした．
swimmy起動時に，指定したメッセージをSlackに投稿する方法の例を以下に示す．
```
$ bundle exec exe/swimmy --hello 起動しました！
```
> Add restart command and hello option

- lib/swimmy/app.rb
- lib/swimmy/command/restart.rb
#45 #56 へのPRである．
以下の議事録の内容に基づいて，変更を行った．
+ swimmyが再接続された場合にも起動メッセージが表示されるため，メッセージをキューで管理することで，起動時の1回のみ表示されるようにした．
+ “exe/swimmy”へのパスがプログラム中に埋め込まれているため，“$0”を用いて実行ファイルを指定するようにした．
+ 絶対パスを使うときはexpand_pathを使うと良い．
+ $0が存在するかをチェックする必要がある．
+ 1つのキューに入れて，キューから取り出した際にスプリットした方が良い．
変更内容は，以下の通りである．
+ `lib/swimmy/command/restart.rb`について
+ expand_pathを使って実行ファイルの絶対パスを出すようにした．
+ $0が存在するかどうかを確認するようにした．
+ `lib/swimmy/app.rb`について
+ helloオプションのメッセージをキューから取り出した後にチャンネル名と表示したい文字列に分割するようにした．
> メッセージ分割のタイミングを変更した．また，expand_pathで絶対パスを指定するようにした．

- Gemfile
- Gemfile.lock
- lib/swimmy/command/update.rb
#78 に対するPR
1. when update failed, swimmy send error message to slack
2. if no change, swimmy notify that already up to date
3. add --ff-only option to "git pull" command
> Modify update command

- lib/swimmy/command/now.rb
- lib/swimmy/resource.rb
- lib/swimmy/resource/anniversary.rb
- lib/swimmy/service.rb
- lib/swimmy/service/anniversary.rb
- spec/now_spec.rb
- 時報+αを表示する`now`コマンド（`117`コマンド）の実装
- 乃村研のB4向け新人研修に取り組むため
-  [新人研修課題](https://scrapbox.io/nompedia/swimmy_%E3%81%AE%E6%A9%9F%E8%83%BD%E8%BF%BD%E5%8A%A0)
`/swimmy [now|117]/` と入力し，時報を表示する
- 日時のデータを受け取り，その日が何の記念日かを取得する機能
- wikipedia の API を使用しました https://www.mediawiki.org/wiki/API:Main_page
- ほぼスクレイピングのようなものなので， wikipedia 側のレイアウト変更には弱いです（正規表現である程度柔軟性は持たせています）
- https://ja.wikipedia.org/wiki/%E6%97%A5%E6%9C%AC%E3%81%AE%E8%A8%98%E5%BF%B5%E6%97%A5%E4%B8%80%E8%A6%A7 のページの内容を取得
- ↑で生成した文字列を Slack 上に通知する機能
> Add now command

- lib/swimmy/command/tide.rb
- spec/tide_spec.rb
- 潮の情報を表示する'tide'コマンドの実装
- 乃村研のB4向け新人研修に取り組むため
-  [新人研修課題](https://scrapbox.io/nompedia/swimmy_%E3%81%AE%E6%A9%9F%E8%83%BD%E8%BF%BD%E5%8A%A0)
`/swimmy tide/` ， `/swimmy tide YYYY-MM-DD/` ， `/swimmy tide MM-DD/` のいずれかを入力し，潮の情報を表示する
- 日時のデータを受け取り，その日の潮の情報を取得する機能
- 潮のapiは https://tide736.net/ のものを使用しました
- apiで取得した情報以外に最も潮の早い時間(満潮と干潮の中間)を計算し表示しています
> Add "tide.rb & tide_spec.rb"

- lib/swimmy/command/stock.rb
- 株価の情報を表示するコマンドの実装
- 乃村研B4向けの新人研修課題に取り組むため
- [新人研修課題](https://scrapbox.io/nompedia/swimmy_%E3%81%AE%E6%A9%9F%E8%83%BD%E8%BF%BD%E5%8A%A0)
`/swimmy stock/`または`/swimmy stock XXXX/`と入力し，情報を表示する
- 日経平均株価または指定されたコードの株価を取得する機能
- 株価のAPIはhttps://query1.finance.yahoo.com/v8/finance/chart/ を使用しました
- 始値，高値，安値，終値と前日比を表示します
> Add stock command

- Gemfile
- Gemfile.lock
- lib/swimmy/command/at.rb
- lib/swimmy/resource/schedule.rb
- spec/at_spec.rb
#92 ， #98 に対するPR
1. at コマンドのバグの修正
2. at コマンドのテストの追加
1. Date 型から Time 型 への変換の際にタイムゾーンの情報を含むように修正
2. exec_time の計算時に，eval を用いた計算から，enumdate を用いたものに変更
1. calc_next_time の返り値を確認するテストを追加
> Fix at command

- lib/swimmy/command/at.rb
- lib/swimmy/resource/schedule.rb
平日のみ毎日実行するオプションを追加した．
1. lib/swimmy/resource/schedule.rb
* Interval クラスに WDAY 定数を追加
* Interval が WDAY だった場合，Enumdate を用いて平日のみを対象とする Enumerator を作成するように追加
2. lib/swimmy/command/at.rb
* help に weekdayオプションに関する情報を追記
> Allow to specify weekday option

- lib/swimmy/command/whois.rb
whoisコマンドの追加
lib/swimmy/command 以下に whois.rb を追加した．
今まで在籍していた研究室のメンバについて以下の5つの情報を表示する．
1. 学生番号
2. 氏名
3. 学年
4. メールアドレス
5. 所属
`swimmy whois <keyword>`と入力する．
Google Spread Sheet の API を使用している．
> Add whois command

- lib/swimmy/command/at.rb
- lib/swimmy/command/attendance.rb
- lib/swimmy/command/memo.rb
以下のプログラムに関して，Slackにおける氏名(real_name)を使用していた部分を表示名(display_name)を使用するように変更した．
1. lib/swimmy/command/at.rb
2. lib/swimmy/command/attendance.rb
3. lib/swimmy/command/memo.rb
> Change to use display_name where real_name was used.

- lib/swimmy/command/search_restaurant.rb
- lib/swimmy/resource.rb
- lib/swimmy/resource/restaurant.rb
- lib/swimmy/service.rb
- lib/swimmy/service/restaurant_info.rb
search_restaurantコマンドの追加
- lib/swimmy/command以下にsearch_restaurant.rbを追加した
- lib/swimmy/resource以下にrestaurant.rbを追加した
- lib/swimmy/service以下にrestaurant_info.rbを追加した
入力された検索ワードからホットペッパーのサービスを利用して飲食店の検索を行う．
検索によって得られた検索結果の中から1店舗を選出し，以下の情報を出力する
- 店舗名
- 住所
- 営業時間
-  ホットペッパーのURL
Slack上で`/swimmy search_restaurant XXXX/`と入力する
(`XXXX`には検索したいワードが入る)
ホットペッパーのWebAPIを使用している
[ホットペッパー | APIリファレンス | リクルートWEBサービス](https://webservice.recruit.co.jp/doc/hotpepper/reference.html)
> Add search_restaurant command

- exe/swimmy
swimmy の起動時に command の help において envファイルの情報を読み込むことができず，エラーで止まる．
`require "swimmy"`の時に各コマンドの help が実行されるが，`require "swimmy"`よりも後に exe/swimmy の`Dotenv.load`が実行される．そのため，help 内で envファイルの情報を使用する場合エラーで止まる．
exe/swimmy において`Dotenv.load`が`require swimmy`より先に実行されるように変更した．
> Change require order for dotenv

- lib/swimmy/command/upcoming.rb
- lib/swimmy/resource.rb
- lib/swimmy/resource/event.rb
- lib/swimmy/service.rb
- lib/swimmy/service/calendar_service.rb
upcomingコマンドの実装
- lib/swimmy/command 以下に upcoming.rb を追加
- lib/swimmy/service 以下に calendar_service.rb を追加
- lib/swimmy/resource 以下に event.rb を追加
コードレビューに基づいてコードの内容を変更しました．
1ヶ月先までの全ての予定を表示，またはこのうちキーワードで知りたい予定を絞り込み表示する．
- Slackのnomlabワークスペースで `swimmy upcoming` と入力して1ヶ月先までの予定を表示する．
- Slackのnomlabワークスペースで `swimmy upcoming <keyword>` と入力して1ヵ月先までの予定のうち<keyword\>を含む予定のみ表示する．
- Google Calendar APIを使用している．
> Add upcoming command

- lib/swimmy/command/pollen.rb
- lib/swimmy/resource.rb
- lib/swimmy/resource/pollen_resource.rb
- lib/swimmy/service.rb
- lib/swimmy/service/city_code.rb
- lib/swimmy/service/pollen_service.rb
pollenコマンドの実装
- lib/swimmy/command 以下に pollen.rb を追加
- lib/swimmy/service 以下に pollen_service.rb を追加
- lib/swimmy/service 以下に city_code.rb を追加
- lib/swimmy/resource 以下に pollen_resource.rb を追加
- lib/swimmy/service.rb を pollen_service.rb に定義している Pollen クラスを読み込むように変更
- lib/swimmy/service.rb を city_code.rb に定義している CityCode クラスを読み込むように変更
- lib/swimmy/resource.rb を pollen_resource.rb に定義している Pollen クラスを読み込むように変更
コードレビューで頂いたアドバイスを受けて，コードの修正をしました．
指定した市区町村の1時間前の花粉情報を表示する．
- Slack の nomlab ワークスペースで `swimmy pollen` と入力して岡山市北区の1時間前までの花粉情報を表示する．
- Slack の nomlab ワークスペースで `swimmy pollen <place>` と入力して指定した place の1時間前までの花粉情報を表示する．
-都道府県コードと市区町村コードを ExcelAPI から取得するにあたり，非同期処理で実装している．
> Add pollen information command

- .env.sample
- lib/swimmy/command/openhab.rb
- lib/swimmy/resource.rb
- lib/swimmy/resource/openhab_metadata.rb
- lib/swimmy/service.rb
- lib/swimmy/service/openhab.rb
openhab コマンドの追加
指定されたキーワードに応じた，openHAB 上で管理されている情報を表示する．
`swimmy openhab <キーワード>` と入力する．
`swimmy help openhab` と入力して helpコマンドを使用することで使用可能なキーワードの一覧を表示する．
[openHAB の REST API](https://www.openhab.org/docs/configuration/restdocs.html) を使用している．
> Add openhab command

- lib/swimmy/command/hbday.rb
- lib/swimmy/resource/member.rb
hbday コマンドの追加
- お祝いメッセージを作成する処理をコマンドの方に記述した．
- BirthdayMembersクラスをActiveMembersクラスに変更し，在籍メンバを取り出すメソッドのみを定義した．
- active_membersの要素を一つずつ取り出して，誕生日の判定とお祝いメッセージの表示を一つのループ内で行うようにした．
コードレビューで頂いたアドバイスを基に，コードを修正しました．
研究室メンバのうち，その日誕生日の人をお祝いする．
`swimmy hbday` と入力する．
名簿から在籍メンバの誕生日情報を取得し，それをその日の日付と比較する．
> Add hbday command

- lib/swimmy/command/nomnichi.rb
- lib/swimmy/resource.rb
- lib/swimmy/resource/nomnichi_article.rb
- lib/swimmy/service.rb
- lib/swimmy/service/nomnichi.rb
+ nomnichi のデプロイ先の変更による URL の変更に対応した．
+ swimmy の nomnichi コマンドが Sheetq の Resourse ファイルと Service ファイルに依存していたため，Resourse ファイルと Service ファイルを swimmy に移行した．
+ リクエスト先の URL を変更した．
+ SSL 証明書を無視する設定とそれに伴うメソッドを変更した．
+ Sheetq の Resourse ファイルと Service ファイルを移行した．
> Fix handling nomnichi's HTTP request by ignoring SSL verification

- lib/swimmy/resource/coop_info.rb
+ swimmy coop コマンドが利用できない問題があった
+ @time に"休業\n"が入ったときに対応できていなかった
+ 条件分岐を追加し，”休業”に対応した
> Update coop command supported for 休業

- .env.sample
- lib/swimmy/command/cook.rb
- lib/swimmy/resource.rb
- lib/swimmy/resource/cook_resource.rb
- lib/swimmy/service.rb
- lib/swimmy/service/recipe_information.rb
cook コマンドの追加
指定された食材や料理に適したレシピの情報を表示する．
`swimmy cook <キーワード>` と入力するとキーワードに適したレシピを表示する．
`swimmy cook` と入力するとランダムにレシピを表示する．
[楽天レシピカテゴリ一覧API](https://webservice.rakuten.co.jp/documentation/recipe-category-list)と[楽天レシピカテゴリ別ランキングAPI](https://webservice.rakuten.co.jp/documentation/recipe-category-ranking)を使用している．
> Add cook command

- lib/swimmy/resource/coop_info.rb
+ swimmy coop コマンドが利用できない問題があった
+ 営業時間を取得する部分で，"xx:yy～xx:yy\n" という時間を表す文字列を期待していたが，夏季休業中のため，"休業\n" という文字列や，"休業\n 厨房メンテナンスの為"という文字列が含まれており，対応できていなかった
+ 条件分岐を追加し，時間を表す文字列ではない文字列にも対応するようにした
+ "～" に着目し，"～" が 含まれていれば，時間として処理するようにした
> Update coop command supported for string that is not indicating time

- lib/swimmy/command/photo_upload.rb
一つのメッセージに複数の写真がある場合，2枚目以降の写真のアップロードが必ず失敗するバグを修正した．
写真のアップロード処理をスレッドを用いて並列化していたが，Google Photos は同時に写真がアップロードされると "429 Too Many Requests" を返すことが原因．
複数の写真がある場合，一枚ずつブロッキング処理でアップロードするように変更．
> Fix a bug that uploading multiple photos fails

- .github/workflows/swimmy.yml
- Gemfile.lock
1. slack_socket_mode_bot のバージョンが古く，引数が一致していない問題を解決するために，Gemfile.lock を更新した．
2. GitHub Actions で使用されている Ruby のバージョンが古く，gem の依存関係を解決できない問題を解消するために，GitHub Actions で使用される Ruby のバージョンを 2.7.8 に更新した．
> Bump up dependencies and ruby version for GitHub Actions

- lib/swimmy/command/bookmark.rb
- lib/swimmy/resource.rb
- lib/swimmy/resource/bookmark.rb
- lib/swimmy/service.rb
- lib/swimmy/service/bookmark.rb
bookmark コマンドの追加
よく閲覧する URL のブックマークを追加，削除，表示をする．
`swimmy bookmark` と入力すると，入力したユーザの登録しているブックマークを全件表示する．
`swimmy bookmark add <URL> <title>` と入力すると，URL を title と名付けてブックマークに登録できる．title がない場合，無題として登録される．
`swimmy bookmark delete <target>`と入力すると，target で指定した番号，タイトル，URL のいずれかでマッチしたブックマークを削除する． 
Sheetq を介して Google Sheets を使用して，ユーザごとにブックマークを管理している．
> Add bookmark command

- lib/swimmy/command/location.rb
loc コマンドの追加
ドアプレートの状態を引数で指定された所在に変更する．
`swimmy loc <引数>` と入力するとドアプレートの状態を<引数>に対応した所在に変更する．
<引数>と所在の対応は以下のとおりである．
106号室
|引数|所在|
| ---- | ---- |
| hi | 在室 |
| lecture | 講義 |
| meeting | 打合 |
| campus | 学内 |
| outside | 学外 |
| bye | 帰宅 |
206号室
|引数|所在|
| ---- | ---- |
| hi | 在室 |
| meeting | オンライン講義・会議中 |
| laboratory | 研究室(105・106) |
| lecture | 講義室 |
| department | 学科内 |
| campus | 大学内 |
| bye | 帰宅・出張 |
<引数>の入力には正式名称だけでなく，引数を一意に区別できる文字列を指定できる．
たとえば，所在を``講義''に変更する場合には，<引数>に" l "や " lec " ，"lecture"が指定できる．
MQTT 通信を利用し， openHAB を通じてドアプレートの状態を変更している．
> Add loc command

- lib/swimmy/command/karaoke.rb
- lib/swimmy/service.rb
- lib/swimmy/service/karaoke.rb
karaoke コマンドの追加
DAMのカラオケランキングを表示する．
`swimmy karaoke [引数]` と入力すると[引数]に対応した期間のカラオケランキングを表示する．
[引数]と期間の対応は以下のとおりである．
|引数|期間|
| ---- | ---- |
| daily | デイリーランキング |
| weekly | ウィークリーランキング |
| monthly | マンスリーランキング |
| 引数なし | デイリーランキング | 
DAMの公式サイトからスクレイピングしてランキングを取得している．
> Add karaoke_cmd

- lib/swimmy/command/attendance.rb
+ attendance コマンドを，引数でユーザ名を指定して実行できるようにアップデートした．
+ 引数が指定された場合，そのユーザ名で attendance コマンドを実行する．このとき，指定されたユーザ名が現役メンバのものでない場合は，attendance コマンドは失敗し，エラーメッセージを出力する．
+ 引数が指定されなかった場合，従来どおり，コマンドの発言者のユーザ名で attendance コマンドを実行する．
+ また，上記に伴い，help コマンドで表示するヘルプメッセージをアップデートした．
> Update attendance command to be able to execute with a user name.

- .env.sample
- lib/swimmy/command/hizuki.rb
- lib/swimmy/service.rb
- lib/swimmy/service/numbersapi.rb
- lib/swimmy/service/translate.rb
hizuki コマンドの追加
引数に指定した年や月日に起きたとされる出来事を表示する．
`swimmy hizuki <引数>` と入力すると引数に指定した年や月日に起きたとされる出来事を表示する．
<引数>が受け付ける内容は以下のとおりである．
・現在の西暦より小さい0以外の整数
・<月>/<日>の書式で入力された存在する月日
出来事の英語情報を取得するためにNumbers APIを利用し，英語を翻訳するためにGASで作成した翻訳プログラムを使用している．
> add hizuki command
